# Generated by Django 2.2.1 on 2020-11-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='address',
        ),
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.AddField(
            model_name='students',
            name='clas',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app1.school'),
        ),
    ]
